### ISSUE TITLE
Licensing information has changed

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#103]
I just noticed that the licensing information has changed...earlier there used to be a simplified one line explanation to each license type which is changed now.

![image](https://user-images.githubusercontent.com/10262962/109255542-347ca980-781a-11eb-86fc-30d5784b5e7e.png)

**Comment by apoorv74** [comment]
@karnsaurabhkumar Yes we updated these to accomodate for the other licences that we had not included earlier. They were directly from the prototypes. We dont have the simple 4-5 explanations for all of these at the moment which is why we just kept the titles. 

We're creating a resource page with links to these licences and will add the descriptions once we create those.

**Comment by karnsaurabhkumar** [comment]
Understood
