### ISSUE TITLE
Fix RSS feed link for datasets

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#143]
**Describe the bug**
Not able to access the RSS feed

**Expected behavior**
The RSS feed URL for JH gives an Internal Server Error. [Link](justicehub.in/feeds/dataset.atom)

On OBI, the feeds can be accessed at http://openbudgetsindia.org/feeds/dataset.atom. Also check this StackOverflow [link](https://stackoverflow.com/questions/20031380/where-can-i-find-an-rss-or-atom-feed-of-new-or-changed-datasets-in-ckan)

**Additional context**
On checking the feed for one of the datasets on OBI, the head section contains link to a feed

![image](https://user-images.githubusercontent.com/5118689/126336856-b653303b-5a8b-41a1-9cf7-64c01cb799bd.png)

[Link](https://github.com/cbgaindia/ckanext-openbudgetsin_theme/blob/master/ckanext/openbudgetsin_theme/templates/organization/read_base.html) to template file where the links are getting generated

**Comment by Abhi2102** [comment]
Fixes
- The solr query changes in "Package_show" action  for handling dataset filter related use cases was was creating some and resulting in server error. That was fixed and tested. 
- The links for dataset in the feed generated was giving error, as the feed generation code was using "Package_read" action which was deprecated and replaced by "Package_show" after Ckan 2.6. So, added support for "Package_read" action.
- The links for the dataset in the feed generated were api links and was returning Json instead of the dataset page on the platform. So, changed that behaviour to add actual dataset page as link instead of api link in the feed generated.

All the changes were done in "ckanext-justicehub_theme" code base.
