### ISSUE TITLE
Issues identified during the upload process

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#38]
- [x]  For the question - _Which time period does this data cover?_ , since the month is optional, we should not have January selected as the default month. It gives an impression that Jan will be selected by default
- [x] Add date of publication as an optional field in the data relevancy section - This is missing currently
- [x] Making section logos clickable - A user should be able to move sections by clicking on the section logos
- [x] Show the link on the dialog box after dataset is created. Preview message - _Dataset created successfully - View [here](link)_
- [x] The URL after closing the success pop up is - _/message/success_ This might confuse users, can we point the URL to the homepage itself ?
- [x] In the question - _Who is the Primary Publisher or Author of the file(s)?_ we dont see the organisation detail input field when the org is selected. Ideally Author's Name and Individual should be replaced by org input fields - Org Name and Org email
- [x] Not able to add publisher details in case of an organisation
- [x] Change the dialog msg when saving as Draft - "Dataset saved as a draft - View here"

**Comment by akkisagiraju** [comment]
- [x]  For the question - _Which time period does this data cover?_ , since the month is optional, we should not have January selected as the default month. It gives an impression that Jan will be selected by default
Done. The default month will now be displayed as '--' with its value as an empty string.

- [ ] Add date of publication as an optional field in the data relevancy section - This is missing currently
Is this an extra field we are supposed to add? We've only added the fields that are in the prototype.

- [x] Making section logos clickable - A user should be able to move sections by clicking on the section logos
Done.

- [ ] Show the link on the dialog box after dataset is created. Preview message - _Dataset created successfully - View [here](link)_
- [ ] The URL after closing the success pop up is - _/message/success_ This might confuse users, can we point the URL to the homepage itself ?
ckanext moderation is handling this part. @shashank-sharma I'm assuming you are taking care of these two.

- [x] In the question - _Who is the Primary Publisher or Author of the file(s)?_ we dont see the organisation detail input field when the org is selected. Ideally Author's Name and Individual should be replaced by org input fields - Org Name and Org email
- [x] Not able to add publisher details in case of an organisation
Made changes. Now when someone selects Organization, the previous input fields for Individual authors will be removed and they will switched to Organization inputs. And vice versa for Individuals.

- [ ] Change the dialog msg when saving as Draft - "Dataset saved as a draft - View here"
I'm leaving this to @shashank-sharma.

**Comment by apoorv74** [comment]
- [ ] Include a message for the user that we only allow file uploads that are less than 100 Mb's in size. For larger files, please reach out to tech@justicehub.in

**Comment by Abhi2102** [comment]
The pop related issues are fixed.
